rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1

language: ruby

cache: bundler

services:
  - mongodb
  - redis-server

install:
  - export BUNDLE_GEMFILE=$PWD/Gemfile
  - bundle install --deployment --path=${BUNDLE_PATH:-vendor/bundle}
  - cd cli
  - export BUNDLE_GEMFILE=$PWD/Gemfile
  - bundle install --deployment --path=${BUNDLE_PATH:-vendor/bundle}

script:
  - 'cd $TRAVIS_BUILD_DIR && contrib/ci/ci-client.sh'
