# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "Peas"
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tom Buckley-Houston"]
  s.date = "2014-04-06"
  s.description = "Peas is an open source Heroku-style PaaS written in Ruby and using Docker"
  s.email = "tom@tombh.co.uk"
  s.executables = ["peas"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "Peas.gemspec",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/peas",
    "lib/peas.rb",
    "lib/peas/api.rb",
    "lib/peas/config.rb",
    "lib/peas/git.rb",
    "lib/peas/version.rb",
    "spec/cli_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/tombh/peas"
  s.licenses = ["GPL v2"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.14"
  s.summary = "CLI client for Peas"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<gli>, [">= 0"])
      s.add_runtime_dependency(%q<httparty>, [">= 0"])
      s.add_runtime_dependency(%q<rainbow>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<gli>, [">= 0"])
      s.add_dependency(%q<httparty>, [">= 0"])
      s.add_dependency(%q<rainbow>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<gli>, [">= 0"])
    s.add_dependency(%q<httparty>, [">= 0"])
    s.add_dependency(%q<rainbow>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

