# encoding: utf-8

require 'rubygems'
require 'bundler'
begin
  Bundler.setup(:default, :development)
rescue Bundler::BundlerError => e
  $stderr.puts e.message
  $stderr.puts "Run `bundle install` to install missing gems"
  exit e.status_code
end
require 'rake'

require 'jeweler'
require './lib/peas/version.rb'
Jeweler::Tasks.new do |gem|
  # gem is a Gem::Specification... see http://guides.rubygems.org/specification-reference/ for more options
  gem.name = "peas-cli"
  gem.homepage = "http://github.com/tombh/peas"
  gem.license = "GPL v2"
  gem.version = Peas::VERSION
  gem.summary = "CLI client for Peas"
  gem.description = "Peas is an open source Heroku-style PaaS written in Ruby and using Docker"
  gem.email = "tom@tombh.co.uk"
  gem.authors = ["Tom Buckley-Houston"]
  gem.files.include 'VERSION'
  # Don't include peas-dev
  gem.executables = ['peas']
  gem.files.exclude 'bin/peas-dev'
  # dependencies defined in Gemfile
end
Jeweler::RubygemsDotOrgTasks.new

desc "Code coverage detail"
task :simplecov do
  ENV['COVERAGE'] = "true"
  Rake::Task['test'].execute
end
